name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: |
        mkdir -p ./build/addons/sourcemode/plugins/ImbaManagerPlugin
        dotnet publish imba-manager-csharp-plugin.sln -c Release -o ./build/addons/counterstrikesharp/plugins/ImbaManagerPlugin
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cs2-imba-manager-plugin
        path: ./build